//! The CASH money cycle, end to end, on local regtest nodes.
//!
//! One run proves, with real BeamHash III blocks and the real `cyphes-wallet`
//! CLI:
//!
//! 1. mine and receive: a wallet detects mined rewards and applies the
//!    100-confirmation coinbase policy;
//! 2. spend: A pays B, and balances reconcile with change and fee;
//! 3. restore: a fresh database restored from seed and birthday reproduces
//!    the balance and history;
//! 4. reorganisation: two nodes build competing branches, a payment is
//!    orphaned, and wallets follow the winning chain and recover;
//! 5. invalid spends sent straight to the node, bypassing wallet checks:
//!    double spend, unknown anchor, broken value conservation;
//! 6. above 21 million: a real mined note above 21 million CASH is
//!    created, received and spent (on a regtest node configured with a
//!    25 million CASH block subsidy).
//!
//! Every block is mined, so this takes about 40 minutes and needs about 10 GiB
//! of RAM. Build the node first, then run it explicitly:
//!
//! ```sh
//! cargo build -p zebrad --features internal-miner
//! cargo test -p cyphes-wallet --test money_cycle -- --ignored --nocapture
//! ```
//!
//! Evidence is written to `target/money-cycle/REPORT.md`.

use std::{
    fs,
    io::{Read, Write},
    net::TcpStream,
    path::{Path, PathBuf},
    process::{Child, Command, Stdio},
    time::{Duration, Instant},
};

use serde_json::{json, Value};

const COIN: u64 = 100_000_000;

/// The public devnet address (see `devnet/regtest.toml`); blocks that should
/// not pay the wallets under test are mined to it.
const DEVNET_MINER: &str = "cyphregtest1gymj99nyn4c9n68u3vcuqlr57p8evnukeqfnt5l3tvnq0na2amv6tz270dwfnzrg8x63yhvskqgalaewgnqy6zts0842s3w2esyrtye0";

fn workspace() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .to_owned()
}

/// Evidence collected for the report.
struct Report {
    path: PathBuf,
    lines: Vec<String>,
    started: Instant,
}

impl Report {
    fn new(path: PathBuf) -> Self {
        let mut report = Report {
            path,
            lines: Vec::new(),
            started: Instant::now(),
        };
        report.line("# CASH money cycle: evidence");
        report.line("");
        report.line(
            "Generated by `cyphes-wallet/tests/money_cycle.rs`. Every block below was mined with a",
        );
        report.line(
            "real BeamHash III solution on a local regtest node that validates proof of work.",
        );
        report
    }

    fn line(&mut self, line: impl Into<String>) {
        let line = line.into();
        println!("{line}");
        self.lines.push(line);
        self.flush();
    }

    fn section(&mut self, title: &str) {
        self.line("");
        self.line(format!("## {title}"));
        self.line("");
    }

    fn check(&mut self, ok: bool, claim: impl Into<String>) {
        let claim = claim.into();
        self.line(format!("- {} {claim}", if ok { "PASS" } else { "FAIL" }));
        assert!(ok, "{claim}");
    }

    fn flush(&self) {
        let _ = fs::write(&self.path, self.lines.join("\n") + "\n");
    }
}

impl Drop for Report {
    fn drop(&mut self) {
        self.lines.push(String::new());
        self.lines
            .push(format!("Run time: {:.0?}.", self.started.elapsed()));
        self.flush();
    }
}

/// A zebrad regtest node with persistent state.
struct Node {
    name: String,
    dir: PathBuf,
    p2p: u16,
    rpc: u16,
    grpc: u16,
    child: Option<Child>,
}

impl Node {
    fn new(root: &Path, name: &str, base_port: u16, testnet_parameters: &str) -> Node {
        let dir = root.join(name);
        fs::create_dir_all(&dir).expect("node dir");
        let (p2p, rpc, grpc) = (base_port, base_port + 1, base_port + 2);
        let config = format!(
            r#"[mining]
internal_miner = false
miner_address = "{DEVNET_MINER}"

[network]
network = "Regtest"
listen_addr = "127.0.0.1:{p2p}"
initial_mainnet_peers = []
initial_testnet_peers = []
cache_dir = false
{testnet_parameters}

[rpc]
listen_addr = "127.0.0.1:{rpc}"
lightwalletd_listen_addr = "127.0.0.1:{grpc}"
enable_cookie_auth = false

[state]
cache_dir = "{state}"
ephemeral = false

[tracing]
use_color = false
"#,
            state = dir.join("state").display(),
        );
        fs::write(dir.join("zebrad.toml"), config).expect("node config");
        Node {
            name: name.into(),
            dir,
            p2p,
            rpc,
            grpc,
            child: None,
        }
    }

    fn start(&mut self) {
        let zebrad = std::env::var_os("CYPHES_ZEBRAD")
            .map(PathBuf::from)
            .unwrap_or_else(|| workspace().join("target/debug/zebrad"));
        assert!(
            zebrad.exists(),
            "build the node first: cargo build -p zebrad --features internal-miner"
        );
        let log = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(self.dir.join("zebrad.log"))
            .expect("node log");
        let child = Command::new(zebrad)
            .arg("-c")
            .arg(self.dir.join("zebrad.toml"))
            .arg("start")
            .stdout(log.try_clone().expect("log"))
            .stderr(log)
            .spawn()
            .expect("start zebrad");
        self.child = Some(child);
        let deadline = Instant::now() + Duration::from_secs(120);
        while self.try_rpc("getblockcount", json!([])).is_err() {
            assert!(Instant::now() < deadline, "{} did not start", self.name);
            std::thread::sleep(Duration::from_millis(500));
        }
        // Give the light-wallet gRPC server a moment to bind.
        std::thread::sleep(Duration::from_secs(2));
    }

    fn stop(&mut self) {
        if let Some(mut child) = self.child.take() {
            let _ = Command::new("kill")
                .arg("-TERM")
                .arg(child.id().to_string())
                .status();
            let deadline = Instant::now() + Duration::from_secs(30);
            while child.try_wait().ok().flatten().is_none() && Instant::now() < deadline {
                std::thread::sleep(Duration::from_millis(250));
            }
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    fn grpc(&self) -> String {
        format!("http://127.0.0.1:{}", self.grpc)
    }

    fn peer_addr(&self) -> String {
        format!("127.0.0.1:{}", self.p2p)
    }

    fn try_rpc(&self, method: &str, params: Value) -> Result<Value, String> {
        let body =
            json!({ "jsonrpc": "2.0", "id": 1, "method": method, "params": params }).to_string();
        let mut stream = TcpStream::connect(("127.0.0.1", self.rpc)).map_err(|e| e.to_string())?;
        write!(
            stream,
            "POST / HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
            body.len()
        )
        .map_err(|e| e.to_string())?;
        let mut response = String::new();
        stream
            .read_to_string(&mut response)
            .map_err(|e| e.to_string())?;
        let (head, body) = response
            .split_once("\r\n\r\n")
            .ok_or("malformed HTTP response")?;
        let body = if head
            .to_ascii_lowercase()
            .contains("transfer-encoding: chunked")
        {
            dechunk(body)
        } else {
            body.to_string()
        };
        let value: Value = serde_json::from_str(&body).map_err(|e| format!("{e}: {body}"))?;
        match value.get("error") {
            Some(error) if !error.is_null() => Err(error.to_string()),
            _ => Ok(value["result"].clone()),
        }
    }

    fn rpc(&self, method: &str, params: Value) -> Value {
        self.try_rpc(method, params.clone())
            .unwrap_or_else(|e| panic!("{} {method} {params}: {e}", self.name))
    }

    fn mine(&self, blocks: u32, to: &str) {
        self.rpc("generatetoaddress", json!([blocks, to]));
    }

    fn height(&self) -> u32 {
        self.rpc("getblockcount", json!([]))
            .as_u64()
            .expect("height") as u32
    }

    fn tip_hash(&self) -> String {
        self.rpc("getbestblockhash", json!([]))
            .as_str()
            .expect("hash")
            .to_string()
    }
}

impl Drop for Node {
    fn drop(&mut self) {
        self.stop();
    }
}

fn dechunk(body: &str) -> String {
    let mut out = String::new();
    let mut rest = body;
    while let Some((size, tail)) = rest.split_once("\r\n") {
        let size = usize::from_str_radix(size.trim(), 16).unwrap_or(0);
        if size == 0 {
            break;
        }
        out.push_str(&tail[..size]);
        rest = &tail[size + 2..];
    }
    out
}

/// The `cyphes-wallet` CLI, pointed at one wallet directory and node.
struct Wallet {
    name: String,
    dir: PathBuf,
    server: String,
    coinbase_confirmations: u32,
}

impl Wallet {
    fn new(root: &Path, name: &str, node: &Node) -> Wallet {
        Wallet {
            name: name.into(),
            dir: root.join(name),
            server: node.grpc(),
            coinbase_confirmations: 100,
        }
    }

    fn try_cli(&self, args: &[&str]) -> Result<Value, String> {
        let output = Command::new(env!("CARGO_BIN_EXE_cyphes-wallet"))
            .arg("--wallet")
            .arg(&self.dir)
            .arg("--server")
            .arg(&self.server)
            .arg("--coinbase-confirmations")
            .arg(self.coinbase_confirmations.to_string())
            .args(args)
            .stderr(Stdio::inherit())
            .output()
            .expect("run cyphes-wallet");
        let value: Value = serde_json::from_slice(&output.stdout)
            .map_err(|e| format!("{e}: {}", String::from_utf8_lossy(&output.stdout)))?;
        match value.get("error") {
            Some(error) => Err(error.as_str().unwrap_or_default().to_string()),
            None => Ok(value),
        }
    }

    fn cli(&self, args: &[&str]) -> Value {
        self.try_cli(args)
            .unwrap_or_else(|e| panic!("{} {args:?}: {e}", self.name))
    }

    fn init(&self) -> String {
        let out = self.cli(&["init", "--network", "regtest", "--birthday", "1"]);
        out["address"].as_str().expect("address").to_string()
    }

    fn restore_from(&self, other: &Wallet) -> String {
        let phrase = other.dir.join("seed.txt");
        let out = self.cli(&[
            "restore",
            "--network",
            "regtest",
            "--birthday",
            "1",
            "--phrase-file",
            phrase.to_str().expect("path"),
        ]);
        out["address"].as_str().expect("address").to_string()
    }

    fn sync(&self) {
        self.cli(&["sync"]);
    }

    /// (total, spendable, pending, coinbase_locked) in base units.
    fn balance(&self) -> (u64, u64, u64, u64) {
        let b = self.cli(&["balance"]);
        let get = |k: &str| b["base_units"][k].as_u64().expect("balance field");
        (
            get("total"),
            get("spendable"),
            get("pending"),
            get("coinbase_locked"),
        )
    }

    /// Sends `cash` CASH; returns (txid, fee in base units, raw hex).
    fn send(&self, to: &str, cash: &str, extra: &[&str]) -> Result<(String, u64, String), String> {
        let mut args = vec!["send", "--to", to, "--amount", cash];
        args.extend_from_slice(extra);
        let out = self.try_cli(&args)?;
        let fee = cyphes_wallet::parse_cash(out["fee"].as_str().expect("fee"))
            .expect("fee")
            .into_u64();
        Ok((
            out["txid"].as_str().expect("txid").to_string(),
            fee,
            out["raw"].as_str().expect("raw").to_string(),
        ))
    }

    fn history(&self) -> Vec<Value> {
        self.cli(&["history"])["transactions"]
            .as_array()
            .expect("history")
            .clone()
    }

    /// Copies this wallet's directory to a new wallet (same keys, same state).
    fn snapshot(&self, name: &str) -> Wallet {
        let dir = self.dir.with_file_name(name);
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("snapshot dir");
        for entry in fs::read_dir(&self.dir).expect("wallet dir") {
            let entry = entry.expect("entry");
            fs::copy(entry.path(), dir.join(entry.file_name())).expect("copy wallet file");
        }
        Wallet {
            name: name.into(),
            dir,
            server: self.server.clone(),
            coinbase_confirmations: self.coinbase_confirmations,
        }
    }

    /// Values of the Ironwood notes this wallet has received.
    fn note_values(&self) -> Vec<u64> {
        let conn = rusqlite::Connection::open(self.dir.join("wallet.db")).expect("wallet db");
        let mut stmt = conn
            .prepare("SELECT value FROM ironwood_received_notes ORDER BY id")
            .expect("query");
        stmt.query_map([], |row| row.get::<_, i64>(0))
            .expect("notes")
            .map(|v| v.expect("value") as u64)
            .collect()
    }
}

fn cash(base: u64) -> String {
    cyphes_wallet::format_cash(base)
}

fn nullifiers(raw_hex: &str) -> Vec<[u8; 32]> {
    let raw = hex::decode(raw_hex).expect("hex");
    let tx = zcash_primitives::transaction::Transaction::read(
        &raw[..],
        zcash_protocol::consensus::BranchId::Nu6_3,
    )
    .expect("parse transaction");
    tx.ironwood_bundle()
        .map(|bundle| {
            bundle
                .actions()
                .iter()
                .map(|a| a.nullifier().to_bytes())
                .collect()
        })
        .unwrap_or_default()
}

fn wait_until(what: &str, timeout: Duration, mut done: impl FnMut() -> bool) {
    let deadline = Instant::now() + timeout;
    while !done() {
        assert!(Instant::now() < deadline, "timed out waiting for {what}");
        std::thread::sleep(Duration::from_secs(1));
    }
}

#[test]
#[ignore = "slow: mines ~150 real BeamHash III blocks; see the module docs"]
fn money_cycle() {
    let root = workspace().join("target/money-cycle");
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("output dir");
    let mut report = Report::new(root.join("REPORT.md"));

    // The wallet's coinbase policy. The evidence run uses the default, 100;
    // MONEY_CYCLE_COINBASE_CONFIRMATIONS lowers it to iterate faster.
    let policy: u32 = std::env::var("MONEY_CYCLE_COINBASE_CONFIRMATIONS")
        .ok()
        .map(|v| v.parse().expect("a number"))
        .unwrap_or(100);
    assert!(
        policy >= 13,
        "the checks below need at least 13 confirmations"
    );

    let mut node1 = Node::new(&root, "node1", 23_974, "");
    node1.start();

    // 1. Mine and receive, under the coinbase policy.
    report.section("1. Mine and receive");
    report.line(format!(
        "Wallet coinbase policy: {policy} confirmations{}.",
        if policy == 100 {
            " (the default)"
        } else {
            " (lowered for a quick run; the default is 100)"
        }
    ));
    let mut a = Wallet::new(&root, "alice", &node1);
    let mut b = Wallet::new(&root, "bob", &node1);
    a.coinbase_confirmations = policy;
    b.coinbase_confirmations = policy;
    let a_addr = a.init();
    let b_addr = b.init();
    report.line(format!("Alice `{a_addr}`"));
    report.line(format!("Bob `{b_addr}`"));

    node1.mine(3, &a_addr);
    node1.mine(policy - 4, DEVNET_MINER);
    a.sync();
    let (total, spendable, _, locked) = a.balance();
    report.line(format!(
        "Height {}: blocks 1-3 paid Alice; the block-1 reward has {} confirmations.",
        node1.height(),
        policy - 1
    ));
    report.check(
        total == 3_000 * COIN,
        format!(
            "Alice's wallet holds the three mined rewards: {} CASH",
            cash(total)
        ),
    );
    report.check(
        spendable == 0,
        format!(
            "none is spendable before {policy} confirmations (spendable {})",
            cash(spendable)
        ),
    );
    report.check(
        locked == 3_000 * COIN,
        format!(
            "all of it is locked by the coinbase policy ({})",
            cash(locked)
        ),
    );

    node1.mine(1, DEVNET_MINER);
    a.sync();
    let (_, spendable, _, locked) = a.balance();
    report.check(
        spendable == 1_000 * COIN && locked == 2_000 * COIN,
        format!(
            "at height {policy} exactly the block-1 reward unlocks: spendable {}, locked {}",
            cash(spendable),
            cash(locked)
        ),
    );
    node1.mine(2, DEVNET_MINER);
    a.sync();
    let (_, spendable, _, locked) = a.balance();
    report.check(
        spendable == 3_000 * COIN && locked == 0,
        format!(
            "at height {} all three rewards are spendable: {}",
            policy + 2,
            cash(spendable)
        ),
    );
    let history = a.history();
    report.check(
        history.len() == 3 && history.iter().all(|t| t["is_coinbase"] == json!(true)),
        format!(
            "Alice's history is the three coinbase transactions at heights {:?}",
            history
                .iter()
                .map(|t| t["mined_height"].clone())
                .collect::<Vec<_>>()
        ),
    );

    // Proof of work, checked by the node itself.
    report.section("1b. Proof of work at the node");
    let tip = node1.height();
    let tip_hash = node1.tip_hash();
    let block_hex = node1.rpc("getblock", json!([tip.to_string(), 0]));
    let block = hex::decode(block_hex.as_str().expect("block hex")).expect("hex");
    // Header: 108 bytes of fields, the 8-byte nonce, then the 104-byte solution.
    for (what, at) in [
        ("one bit of its BeamHash III solution", 150),
        ("one bit of its nonce", 110),
    ] {
        let mut mutated = block.clone();
        mutated[at] ^= 1;
        let response = node1.rpc("submitblock", json!([hex::encode(&mutated)]));
        report.check(
            response == json!("rejected"),
            format!("a copy of block {tip} with {what} flipped is rejected ({response})"),
        );
    }
    let response = node1.rpc("submitblock", json!([block_hex]));
    report.check(
        response == json!("duplicate"),
        format!("the unmodified block is already on the chain ({response})"),
    );
    report.check(node1.tip_hash() == tip_hash, "the chain tip is unchanged");

    // 2. Spend.
    report.section("2. Spend");
    let (pay_txid, fee, _) = a.send(&b_addr, "1500", &[]).expect("Alice pays Bob");
    report.line(format!(
        "Alice pays Bob 1500 CASH in `{pay_txid}`, fee {} CASH.",
        cash(fee)
    ));
    report.check(
        fee == 10_000,
        "the fee is ZIP 317's 2-action minimum, 0.0001 CASH",
    );
    node1.mine(1, DEVNET_MINER);
    b.sync();
    let (b_total, b_spendable, b_pending, _) = b.balance();
    report.check(
        b_total == 1_500 * COIN && b_spendable == 0 && b_pending == 1_500 * COIN,
        format!(
            "after 1 confirmation Bob sees {} CASH, pending (ZIP 315: 10 for received value)",
            cash(b_total)
        ),
    );
    node1.mine(9, DEVNET_MINER);
    a.sync();
    b.sync();
    let (a_total, a_spendable, _, _) = a.balance();
    let (b_total, b_spendable, _, _) = b.balance();
    report.check(
        b_spendable == 1_500 * COIN,
        format!(
            "after 10 confirmations Bob can spend {} CASH",
            cash(b_spendable)
        ),
    );
    report.check(
        a_total == 3_000 * COIN - 1_500 * COIN - fee && a_spendable == a_total,
        format!(
            "Alice holds her change: 3000 - 1500 - fee = {} CASH, all spendable",
            cash(a_total)
        ),
    );
    report.check(
        a_total + b_total + fee == 3_000 * COIN,
        "Alice + Bob + fee equals the 3000 CASH mined: nothing created or lost",
    );
    let a_send = a
        .history()
        .into_iter()
        .find(|t| t["txid"] == json!(pay_txid))
        .expect("send in history");
    report.check(
        a_send["delta"].as_i64() == Some(-((1_500 * COIN + fee) as i64)),
        format!(
            "Alice's history records the payment as {} base units",
            a_send["delta"]
        ),
    );
    report.check(
        b.history().iter().any(|t| {
            t["txid"] == json!(pay_txid) && t["delta"].as_i64() == Some((1_500 * COIN) as i64)
        }),
        "Bob's history records the same transaction as +1500 CASH",
    );

    // 3. Restore.
    report.section("3. Restore from seed");
    let mut restored = Wallet::new(&root, "alice-restored", &node1);
    restored.coinbase_confirmations = policy;
    let restored_addr = restored.restore_from(&a);
    restored.sync();
    let (r_total, r_spendable, _, _) = restored.balance();
    let (a_total, a_spendable, _, _) = a.balance();
    report.line("A new database, given only Alice's recovery phrase and birthday 1:");
    report.check(restored_addr == a_addr, "derives the same address");
    report.check(
        (r_total, r_spendable) == (a_total, a_spendable),
        format!(
            "rebuilds the same balance from the chain: {} CASH total, {} spendable",
            cash(r_total),
            cash(r_spendable)
        ),
    );
    let key = |t: &Value| {
        (
            t["txid"].to_string(),
            t["mined_height"].to_string(),
            t["delta"].to_string(),
        )
    };
    let mut a_hist: Vec<_> = a.history().iter().map(key).collect();
    let mut r_hist: Vec<_> = restored.history().iter().map(key).collect();
    a_hist.sort();
    r_hist.sort();
    report.check(
        a_hist == r_hist,
        format!(
            "rebuilds the same history: {} transactions, same txids, heights and amounts",
            r_hist.len()
        ),
    );

    // 4. Reorganisation across two nodes.
    report.section("4. Reorganisation");
    let mut node2 = Node::new(&root, "node2", 24_974, "");
    node2.start();
    node2.rpc("addnode", json!([node1.peer_addr(), "add"]));
    wait_until(
        "node2 to sync node1's chain",
        Duration::from_secs(300),
        || node2.tip_hash() == node1.tip_hash(),
    );
    let fork_height = node1.height();
    report.line(format!(
        "Node 2 syncs node 1's chain to height {fork_height}; then the nodes are separated."
    ));
    node2.stop();

    let (b_before, b_before_spendable, _, _) = b.balance();
    let (orphan_txid, orphan_fee, orphan_raw) =
        a.send(&b_addr, "777", &[]).expect("Alice pays Bob 777");
    node1.mine(1, DEVNET_MINER);
    b.sync();
    let (b_with_payment, _, _, _) = b.balance();
    report.check(
        b_with_payment == b_before + 777 * COIN,
        format!(
            "on node 1's branch Bob receives 777 CASH in block {} (`{orphan_txid}`)",
            fork_height + 1
        ),
    );
    node1.stop();

    node2.start();
    report.check(
        node2.height() == fork_height,
        format!("node 2 restarts with its synced chain intact (height {fork_height})"),
    );
    node2.mine(3, DEVNET_MINER);
    report.line(format!(
        "Node 2, alone, mines 3 blocks to height {}: a longer branch without the payment.",
        node2.height()
    ));

    // An unknown-anchor transaction: valid proofs and signatures, anchored to
    // the tip of node 2's branch, which node 1 has never seen. (Built from a
    // copy of Bob's wallet: Alice's only note is reserved by her payment.)
    let fork_wallet = b.snapshot("bob-on-node2");
    let fork_wallet = Wallet {
        server: node2.grpc(),
        ..fork_wallet
    };
    fork_wallet.sync();
    let (anchor_txid, anchor_fee, anchor_raw) = fork_wallet
        .send(
            &a_addr,
            "11",
            &["--trusted", "1", "--untrusted", "1", "--no-broadcast"],
        )
        .expect("build a transaction on node 2's branch");

    node2.stop();
    node1.start();
    report.check(
        node1.height() == fork_height + 1,
        format!(
            "node 1 restarts with its branch intact (height {})",
            fork_height + 1
        ),
    );
    let rejected = node1.try_rpc("sendrawtransaction", json!([anchor_raw]));
    report.check(
        rejected.is_err(),
        format!(
            "node 1 rejects `{anchor_txid}`, whose anchor is only on node 2's branch: {}",
            rejected.clone().err().unwrap_or_default()
        ),
    );
    report.check(
        rejected
            .err()
            .unwrap_or_default()
            .to_lowercase()
            .contains("unknown ironwood anchor"),
        "the rejection names the unknown Ironwood anchor",
    );

    node2.start();
    node1.rpc("addnode", json!([node2.peer_addr(), "add"]));
    wait_until(
        "node 1 to reorganise onto node 2's branch",
        Duration::from_secs(300),
        || node1.tip_hash() == node2.tip_hash(),
    );
    report.check(
        node1.height() == fork_height + 3,
        format!(
            "node 1 reorganises to node 2's longer branch (height {})",
            node1.height()
        ),
    );
    b.sync();
    let (b_total, b_spendable, b_pending, _) = b.balance();
    report.check(
        b_spendable == b_before_spendable && b_total == b_before + b_pending,
        format!(
            "Bob's wallet follows the reorganisation: the orphaned payment is no longer confirmed; \
             spendable is back to {} CASH",
            cash(b_spendable)
        ),
    );
    report.line(format!(
        "The orphaned 777 CASH now shows as {} (pending {} CASH): the transaction is still \
         valid on the new chain, so the wallet waits to see whether it confirms again.",
        if b_pending == 777 * COIN {
            "unconfirmed"
        } else {
            "gone"
        },
        cash(b_pending)
    ));

    // The orphaned payment is still a valid transaction on the new chain.
    let in_mempool = node1
        .rpc("getrawmempool", json!([]))
        .as_array()
        .is_some_and(|txids| txids.iter().any(|t| t == &json!(orphan_txid)));
    report.line(format!(
        "After the reorganisation the orphaned payment is {}in node 1's mempool{}.",
        if in_mempool { "" } else { "not " },
        if in_mempool {
            ""
        } else {
            "; Alice's wallet broadcasts it again"
        }
    ));
    if !in_mempool {
        node1.rpc("sendrawtransaction", json!([orphan_raw]));
    }
    node1.mine(10, DEVNET_MINER);
    a.sync();
    b.sync();

    // The unknown-anchor transaction was rejected because node 1 did not know
    // its anchor. Node 2's branch, where the anchor exists, has now won, and
    // Zebra retries transactions submitted over RPC, so it may have confirmed.
    let anchor_mined = node1
        .try_rpc("getrawtransaction", json!([anchor_txid, 1]))
        .ok()
        .and_then(|tx| tx["height"].as_u64())
        .is_some();
    report.line(format!(
        "The transaction rejected for its unknown anchor {} on the winning chain, where its anchor exists.",
        if anchor_mined { "has since confirmed, retried by the node," } else { "has not confirmed" }
    ));
    let anchor_spent = if anchor_mined {
        11 * COIN + anchor_fee
    } else {
        0
    };
    let anchor_received = if anchor_mined { 11 * COIN } else { 0 };

    let orphan_mined = node1
        .try_rpc("getrawtransaction", json!([orphan_txid, 1]))
        .ok()
        .and_then(|tx| tx["height"].as_u64())
        .is_some();
    report.check(
        orphan_mined,
        "the orphaned payment confirms on the winning chain",
    );
    // Value received in the last 10 blocks is still pending under ZIP 315.
    let (a_final, a_final_spendable, a_final_pending, _) = a.balance();
    let (b_final, b_final_spendable, b_final_pending, _) = b.balance();
    report.check(
        b_final == b_before + 777 * COIN - anchor_spent
            && b_final_spendable + b_final_pending == b_final,
        format!(
            "Bob's balance matches the winning chain: {} CASH ({} spendable, {} pending)",
            cash(b_final),
            cash(b_final_spendable),
            cash(b_final_pending)
        ),
    );
    report.check(
        a_final == 3_000 * COIN - 1_500 * COIN - fee - 777 * COIN - orphan_fee + anchor_received
            && a_final_spendable + a_final_pending == a_final,
        format!(
            "Alice's balance matches the winning chain: {} CASH ({} spendable, {} pending)",
            cash(a_final),
            cash(a_final_spendable),
            cash(a_final_pending)
        ),
    );

    // 5. Invalid spends, straight to the node.
    report.section("5. Invalid spends rejected by the node");
    let twin = a.snapshot("alice-twin");
    let (t1, _, t1_raw) = a
        .send(&b_addr, "100", &["--no-broadcast"])
        .expect("build t1");
    let (t2, _, t2_raw) = twin
        .send(&b_addr, "200", &["--no-broadcast"])
        .expect("build t2");
    let shared: Vec<_> = nullifiers(&t1_raw)
        .into_iter()
        .filter(|n| nullifiers(&t2_raw).contains(n))
        .collect();
    report.check(
        !shared.is_empty(),
        format!("two copies of Alice's wallet build `{t1}` and `{t2}`, spending the same note"),
    );
    node1.rpc("sendrawtransaction", json!([t1_raw]));
    let mempool_conflict = node1.try_rpc("sendrawtransaction", json!([t2_raw]));
    report.check(
        mempool_conflict.is_err(),
        format!(
            "with the first in the mempool, the node rejects the second: {}",
            mempool_conflict.err().unwrap_or_default()
        ),
    );
    node1.mine(1, DEVNET_MINER);
    let chain_conflict = node1.try_rpc("sendrawtransaction", json!([t2_raw]));
    report.check(
        chain_conflict.is_err(),
        format!(
            "once the first is mined, the node still rejects the second: {}",
            chain_conflict.err().unwrap_or_default()
        ),
    );

    // Any valid transaction will do; a copy of Bob's wallet has free notes.
    let bob_copy = b.snapshot("bob-copy");
    let (t3, t3_fee, t3_raw) = bob_copy
        .send(&a_addr, "50", &["--no-broadcast"])
        .expect("build t3");
    let mut raw = hex::decode(&t3_raw).expect("hex");
    let balance_bytes = (t3_fee as i64).to_le_bytes();
    let at: Vec<usize> = raw
        .windows(8)
        .enumerate()
        .filter(|(_, w)| *w == balance_bytes)
        .map(|(i, _)| i)
        .collect();
    report.check(
        at.len() == 1,
        "the value balance field is located in the serialized transaction",
    );
    let inflated = t3_fee as i64 + (1_000 * COIN) as i64;
    raw[at[0]..at[0] + 8].copy_from_slice(&inflated.to_le_bytes());
    let conservation = node1.try_rpc("sendrawtransaction", json!([hex::encode(&raw)]));
    report.check(
        conservation.is_err(),
        format!(
            "a copy of `{t3}` claiming 1000 CASH more out of the pool than its notes hold is rejected: {}",
            conservation.err().unwrap_or_default()
        ),
    );
    drop(node2);

    // 6. Above 21 million: real mined notes on a node paying 25 million CASH per block.
    report.section("6. Above 21 million CASH");
    node1.stop();
    let mut node3 = Node::new(
        &root,
        "node3",
        25_974,
        "\n[network.testnet_parameters]\nblock_subsidy = 25000000\n",
    );
    node3.start();
    let mut large_a = Wallet::new(&root, "large-a", &node3);
    let mut large_b = Wallet::new(&root, "large-b", &node3);
    // The coinbase policy was proven in section 1; a shorter one keeps this section quick.
    large_a.coinbase_confirmations = 3;
    large_b.coinbase_confirmations = 3;
    let la = large_a.init();
    let lb = large_b.init();
    report.line(
        "A regtest node configured with `block_subsidy = 25000000` (a regtest-only test setting).",
    );
    node3.mine(1, &la);
    // Coinbase notes also need ZIP 315's 10 confirmations for received value.
    node3.mine(10, DEVNET_MINER);
    large_a.sync();
    let (la_total, la_spendable, _, _) = large_a.balance();
    report.check(
        large_a.note_values() == vec![25_000_000 * COIN] && la_spendable == la_total,
        format!("Alice mines a single note of {} CASH", cash(la_total)),
    );
    let (big_txid, big_fee, _) = large_a.send(&lb, "22000000", &[]).expect("send 22 million");
    node3.mine(10, DEVNET_MINER);
    large_b.sync();
    large_a.sync();
    report.check(
        large_b.note_values() == vec![22_000_000 * COIN],
        format!("Bob receives one note of 22,000,000 CASH in `{big_txid}`"),
    );
    let (back_txid, back_fee, _) = large_b
        .send(&la, "21999999", &[])
        .expect("spend the large note");
    node3.mine(10, DEVNET_MINER);
    large_a.sync();
    large_b.sync();
    let (la_total, _, _, _) = large_a.balance();
    let (lb_total, _, _, _) = large_b.balance();
    report.check(
        lb_total == 22_000_000 * COIN - 21_999_999 * COIN - back_fee,
        format!(
            "Bob spends the 22,000,000 CASH note back in `{back_txid}`, keeping {} CASH",
            cash(lb_total)
        ),
    );
    report.check(
        la_total + lb_total + big_fee + back_fee == 25_000_000 * COIN,
        format!(
            "Alice {} + Bob {} + fees = the 25,000,000 CASH mined",
            cash(la_total),
            cash(lb_total)
        ),
    );

    report.section("Result");
    report.line("Every check above passed.");
}
